---
- hosts: minecraft
  become: yes

  tasks:
    - name: Install Java
      dnf:
        name: java-21-amazon-corretto
        state: present

    - name: Create Minecraft directory
      file:
        path: /opt/minecraft
        state: directory
        mode: '0755'

    - name: Download Minecraft server
      get_url:
        url: https://piston-data.mojang.com/v1/objects/e6ec2f64e6080b9b5d9b471b291c33cc7f509733/server.jar
        dest: /opt/minecraft/server.jar

    - name: Accept Minecraft EULA
      copy:
        dest: /opt/minecraft/eula.txt
        content: "eula=true\n"

    - name: Install Minecraft service
      copy:
        src: minecraft.service
        dest: /etc/systemd/system/minecraft.service

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable and start Minecraft
      systemd:
        name: minecraft
        enabled: yes
        state: started
